from pathlib import Path
import json,collections,hashlib
import argparse
p=argparse.ArgumentParser(description='Mechanical aggregate of already-explicit semantic labels; no text classification.')
p.add_argument('--records-dir',required=True,type=Path);p.add_argument('--source-dir',required=True,type=Path);args=p.parse_args()
R=args.records_dir;C=args.source_dir;P='semantic_supervision_20261009T045728Z_';m=json.loads((R/(P+'complete_review_manifest.json')).read_text(encoding='utf-8'));assert hashlib.sha256((C/'case_study.json').read_bytes()).hexdigest()==m['source_case_sha256'];assert hashlib.sha256((R/m['prior_file']).read_bytes()).hexdigest()==m['prior_sha256'];assert hashlib.sha256((R/m['delta_file']).read_bytes()).hexdigest()==m['delta_sha256'];a=json.loads((R/(P+'fullcase_09_12_review.json')).read_text(encoding='utf-8'));d=json.loads((R/(P+'complete_review_delta.json')).read_text(encoding='utf-8'));rs=a['judgments']+d['judgments'];by={r['review_item_id']:r for r in rs};t=json.loads((C/'case_study.json').read_text(encoding='utf-8'));j=json.loads((R/(P+'complete_join.json')).read_text(encoding='utf-8'));u=[r for r in j['fully_reviewed_cases'] if not r['question_target_flag']];rescue=[r for r in u if r['methods']['frozen_reader_topk']['provisional_direct_slot_gap']>0];strict=[r for r in rescue if r['methods']['frozen_reader_topk']['selected_label_counts']['irrelevant']>0];partialonly=[r for r in rescue if r not in strict]
weak={};rankbins=collections.Counter();missbins=collections.Counter()
for c in t['cases']:
 for p in c['candidates']:
  label=by[p['question_passage_review_id']]['support_label'];key='weak_positive' if p['weak_positive'] else 'weak_negative';weak.setdefault(key,collections.Counter())[label]+=1
  if label=='direct':
   rank=p['reader_rank'];bn='1-5' if rank<=5 else '6-10' if rank<=10 else '11-20' if rank<=20 else '21-50';rankbins[bn]+=1
   if rank>5:missbins[bn]+=1
summary={'schema_version':'rag.complete_support_audit_diagnostics.v1','claim_ceiling':'L0_diagnostic','all_audit_cases':32,'all_passages':1600,'remaining':0,'label_counts':dict(collections.Counter(r['support_label'] for r in rs)), 'existing_question_flags_retained':9,'unflagged_not_formally_qualified':len(u),'unflagged_zero_direct_cases':[r['audit_case_number'] for r in u if r['population_label_counts']['direct']==0], 'unflagged_direct_slot_gap_cases':[r['audit_case_number'] for r in rescue],'unflagged_direct_slot_gap_total':sum(r['methods']['frozen_reader_topk']['provisional_direct_slot_gap'] for r in rescue),'unflagged_direct_slot_ceiling':sum(r['provisional_direct_slot_ceiling'] for r in u),'unflagged_reader_direct_selected':sum(r['methods']['frozen_reader_topk']['selected_label_counts']['direct'] for r in u),'provisional_rescue_with_selected_irrelevant_cases':[r['audit_case_number'] for r in strict],'provisional_gap_only_against_selected_partial_cases':[r['audit_case_number'] for r in partialonly], 'weak_label_cross_table':{k:dict(v) for k,v in weak.items()}, 'direct_reader_rank_bins_all_cases_including_flagged':dict(rankbins),'missed_direct_reader_rank_bins_all_cases_including_flagged':dict(missbins), 'training_qualified':False,'independent_blind_review':False,'official_gold':False,'limits':['Counts confined to selected32 old-training questions; not whole434 or heldout100.', 'Direct-slot ceiling is not generator utility, answer accuracy or validated gold oracle.', 'Partial is not a negative; direct-vs-direct preferences not established.', 'Historical/time-specific sources and implicit entailments need independent qualification.', 'No new fitting, inference, train targets or hyperparameter tuning.']}
(R/(P+'complete_diagnostics.json')).write_bytes((json.dumps(summary,ensure_ascii=False,indent=2)+'\n').encode('utf-8'));print(json.dumps(summary,ensure_ascii=False))
